# Generated by Django 3.0.5 on 2024-10-23 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
